name: client
description: "sistema de gestion de inventario"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1  

dependencies:
  excel: ^4.0.6
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4 
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^7.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"  # Icono base para todas las plataformas
  android: true  # Generar icono para Android
  adaptive_icon_background: "#FFFFFF"  # Fondo blanco para iconos adaptativos (Android 8+)
  adaptive_icon_foreground: "assets/icon/icon.png"  # Mismo icono para foreground
  ios: true  # Generar icono para iOS
  remove_alpha_ios: true  # Eliminar canal alfa para iOS (recomendado)
  web:
    generate: true
    background_color: "#FFFFFF"  # Fondo para manifest.json
    theme_color: "#000000"  # Color del tema para la barra del navegador
  windows:
    generate: true
    icon_size: 48  # Tamaño estándar para .ico
  macos:
    generate: true
  linux:
    generate: true