name: client
description: "SENA Gestion de Inventario"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1  # Mantén esta versión por ahora, pero considera actualizar más adelante

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4  # Cambiado de ^10.0.0 a ^9.2.4
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/