name: client
description: "SENA Gestion de Inventario"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1  

dependencies:
  excel: ^4.0.6
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4 
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  mobile_scanner: ^7.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/