services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Puerto externo:puerto interno
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:F2lCLAg76EfRwbd1mkTnC2ZdEuwp8teHyADb7n23YomSk2VI4CipeyW21XZLApIe@147.93.178.204:5433/gestionInventario
      - SECRET_KEY=your-secret-key-here  # Ajuste en produccion
      - APP_PORT=8001
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F2lCLAg76EfRwbd1mkTnC2ZdEuwp8teHyADb7n23YomSk2VI4CipeyW21XZLApIe
      POSTGRES_DB: gestionInventario
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: