services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Puerto externo:puerto interno
    environment:
      - APP_PORT=8001  
    volumes:
      - .:/app
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge