services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Puerto externo:puerto interno
    environment:
      - APP_PORT=8001
    volumes:
      - .:/app
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-8001} --reload"]

networks:
  app-network:
    driver: bridge