"""agregada la columna environment id en la tabla users

Revision ID: 0d81436f59f5
Revises: 0e82d8877a8d
Create Date: 2025-08-09 09:48:18.106458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d81436f59f5'
down_revision: Union[str, Sequence[str], None] = '0e82d8877a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('environment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'environment_id')
    # ### end Alembic commands ###
