"""agregado backpopulate en center

Revision ID: 1a9a09ef9c0e
Revises: e6c868c08667
Create Date: 2025-08-22 12:00:42.296806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9a09ef9c0e'
down_revision: Union[str, Sequence[str], None] = 'e6c868c08667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
