"""agregados status de reviews a inventory_checks

Revision ID: 29217d4f0f86
Revises: eafae79e13c6
Create Date: 2025-08-25 23:35:46.549416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29217d4f0f86'
down_revision: Union[str, Sequence[str], None] = 'eafae79e13c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
