"""agregados check type verification_update en la tabla notifications

Revision ID: 6e04a547aeb0
Revises: 29217d4f0f86
Create Date: 2025-08-25 23:59:59.007789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e04a547aeb0'
down_revision: Union[str, Sequence[str], None] = '29217d4f0f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
