"""agregado eliminacion en cascada para el item

Revision ID: eafae79e13c6
Revises: e05b525f0267
Create Date: 2025-08-25 15:33:32.315205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafae79e13c6'
down_revision: Union[str, Sequence[str], None] = 'e05b525f0267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_items_environment_id_fkey'), 'inventory_items', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_items', 'environments', ['environment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_items_environment_id_fkey'), 'inventory_items', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
